baseurl = "http://www.saroswe.ro"
languageCode = "en-us"
title = "saroswe"
theme = "redlounge"
publishdir = "dist"
[params]
    authorname = "Radu Fericean"
    githubuser = "saroswe"
    copyright = "saroswe"
	sidebartitle = "saroswe"
	sidebartagline = "Evaluarea potentialului productiv, de fitoremediere si adaptabilitate la stresul hidric, a unor genotipuri de Salix sp., in statiuni improprii culturilor agricole!"
[[menu.main]]
    name = "Stiri"
    url = "/post"

